insert into Locations (lid, city, country) values (1, 'Tohong', 'Indonesia');
insert into Locations (lid, city, country) values (2, 'Mekarjaya Satu', 'Indonesia');
insert into Locations (lid, city, country) values (3, 'Charikar', 'Afghanistan');
insert into Locations (lid, city, country) values (4, 'Duran', 'Philippines');
insert into Locations (lid, city, country) values (5, 'Coaraci', 'Brazil');
insert into Locations (lid, city, country) values (6, 'Cimanggu', 'Indonesia');
insert into Locations (lid, city, country) values (7, 'Dmitriyevskaya', 'Russia');
insert into Locations (lid, city, country) values (8, 'Lianghekou', 'China');
insert into Locations (lid, city, country) values (9, 'Yanhu', 'China');
insert into Locations (lid, city, country) values (10, 'Pulosari', 'Indonesia');
insert into Locations (lid, city, country) values (11, 'Kambove', 'Democratic Republic of the Congo');
insert into Locations (lid, city, country) values (12, 'Bandera', 'Argentina');
insert into Locations (lid, city, country) values (13, 'Qijing', 'China');
insert into Locations (lid, city, country) values (14, 'Mumen', 'China');
insert into Locations (lid, city, country) values (15, 'Banyutengah', 'Indonesia');
insert into Locations (lid, city, country) values (16, 'Jiangya', 'China');
insert into Locations (lid, city, country) values (17, 'Néa Tríglia', 'Greece');
insert into Locations (lid, city, country) values (18, 'Gucheng', 'China');
insert into Locations (lid, city, country) values (19, 'Baiba', 'China');
insert into Locations (lid, city, country) values (20, 'Solna', 'Sweden');
insert into Locations (lid, city, country) values (21, 'Hamburg Winterhude', 'Germany');
insert into Locations (lid, city, country) values (22, 'Marićka', 'Bosnia and Herzegovina');
insert into Locations (lid, city, country) values (23, 'Ribeira Seca', 'Portugal');
insert into Locations (lid, city, country) values (24, 'Dongjin', 'China');
insert into Locations (lid, city, country) values (25, 'Santiago De Compostela', 'Spain');
insert into Locations (lid, city, country) values (26, 'Guancheng', 'China');
insert into Locations (lid, city, country) values (27, 'Bay-ang', 'Philippines');
insert into Locations (lid, city, country) values (28, 'Bol’shoy Karay', 'Russia');
insert into Locations (lid, city, country) values (29, 'Vinica', 'Macedonia');
insert into Locations (lid, city, country) values (30, 'San Francisco', 'United States');
insert into Locations (lid, city, country) values (31, 'Gaspra', 'Ukraine');
insert into Locations (lid, city, country) values (32, 'San Ignacio', 'Belize');
insert into Locations (lid, city, country) values (33, 'Al Ma‘baţlī', 'Syria');
insert into Locations (lid, city, country) values (34, 'Dalazi', 'China');
insert into Locations (lid, city, country) values (35, 'Hrvace', 'Croatia');
insert into Locations (lid, city, country) values (36, 'Borovikha', 'Russia');
insert into Locations (lid, city, country) values (37, 'Libuganon', 'Philippines');
insert into Locations (lid, city, country) values (38, 'La Rioja', 'Argentina');
insert into Locations (lid, city, country) values (39, 'Preserje pri Radomljah', 'Slovenia');
insert into Locations (lid, city, country) values (40, 'Kijang', 'South Korea');
insert into Locations (lid, city, country) values (41, 'Dongming Chengguanzhen', 'China');
insert into Locations (lid, city, country) values (42, 'Cipadung Timur', 'Indonesia');
insert into Locations (lid, city, country) values (43, 'El Corozo', 'Venezuela');
insert into Locations (lid, city, country) values (44, 'Pasirmalang', 'Indonesia');
insert into Locations (lid, city, country) values (45, 'Oslo', 'Norway');
insert into Locations (lid, city, country) values (46, 'Ugba', 'Nigeria');
insert into Locations (lid, city, country) values (47, 'Montenegro', 'Colombia');
insert into Locations (lid, city, country) values (48, 'Mojogajeh', 'Indonesia');
insert into Locations (lid, city, country) values (49, 'Fort Smith', 'United States');
insert into Locations (lid, city, country) values (50, 'Yumaguzino', 'Russia');
insert into Locations (lid, city, country) values (51, 'Al Qābil', 'Oman');
insert into Locations (lid, city, country) values (52, 'Kertosari', 'Indonesia');
insert into Locations (lid, city, country) values (53, 'Ikedachō', 'Japan');
insert into Locations (lid, city, country) values (54, 'Zicheng', 'China');
insert into Locations (lid, city, country) values (55, 'Bocana de Paiwas', 'Nicaragua');
insert into Locations (lid, city, country) values (56, 'Rengo', 'Chile');
insert into Locations (lid, city, country) values (57, 'Aparecida', 'Brazil');
insert into Locations (lid, city, country) values (58, 'Xingyi', 'China');
insert into Locations (lid, city, country) values (59, 'Cocobeach', 'Gabon');
insert into Locations (lid, city, country) values (60, 'Hobscheid', 'Luxembourg');
insert into Locations (lid, city, country) values (61, 'San Carlos', 'Colombia');
insert into Locations (lid, city, country) values (62, 'Lugang', 'China');
insert into Locations (lid, city, country) values (63, 'Skibbereen', 'Ireland');
insert into Locations (lid, city, country) values (64, 'Labuhan Deli', 'Indonesia');
insert into Locations (lid, city, country) values (65, 'Larvik', 'Norway');
insert into Locations (lid, city, country) values (66, 'Prigi', 'Indonesia');
insert into Locations (lid, city, country) values (67, 'Dayan', 'China');
insert into Locations (lid, city, country) values (68, 'Mempawah', 'Indonesia');
insert into Locations (lid, city, country) values (69, 'Sete Lagoas', 'Brazil');
insert into Locations (lid, city, country) values (70, 'Lumbardhi', 'Kosovo');
insert into Locations (lid, city, country) values (71, 'Bor', 'Serbia');
insert into Locations (lid, city, country) values (72, 'Kushima', 'Japan');
insert into Locations (lid, city, country) values (73, 'Liancheng', 'China');
insert into Locations (lid, city, country) values (74, 'Quimper', 'France');
insert into Locations (lid, city, country) values (75, 'Karanganyarkrajan', 'Indonesia');
insert into Locations (lid, city, country) values (76, 'Beijie', 'China');
insert into Locations (lid, city, country) values (77, 'Barra de São Francisco', 'Brazil');
insert into Locations (lid, city, country) values (78, 'Petrovskiy', 'Russia');
insert into Locations (lid, city, country) values (79, 'Kréstena', 'Greece');
insert into Locations (lid, city, country) values (80, 'Olofström', 'Sweden');
insert into Locations (lid, city, country) values (81, 'Sapucaia', 'Brazil');
insert into Locations (lid, city, country) values (82, 'Lubuagan', 'Philippines');
insert into Locations (lid, city, country) values (83, 'Marseille', 'France');
insert into Locations (lid, city, country) values (84, 'Hengdian', 'China');
insert into Locations (lid, city, country) values (85, 'Plymouth', 'Montserrat');
insert into Locations (lid, city, country) values (86, 'Łopuszno', 'Poland');
insert into Locations (lid, city, country) values (87, 'Louisville', 'United States');
insert into Locations (lid, city, country) values (88, 'Antipolo', 'Philippines');
insert into Locations (lid, city, country) values (89, 'Bella Vista', 'Dominican Republic');
insert into Locations (lid, city, country) values (90, 'Jutiapa', 'Guatemala');
insert into Locations (lid, city, country) values (91, 'Smilavichy', 'Belarus');
insert into Locations (lid, city, country) values (92, 'Catia La Mar', 'Venezuela');
insert into Locations (lid, city, country) values (93, 'Banyulegi', 'Indonesia');
insert into Locations (lid, city, country) values (94, 'Kirovohrad', 'Ukraine');
insert into Locations (lid, city, country) values (95, 'Zaria', 'Nigeria');
insert into Locations (lid, city, country) values (96, 'Zhoujiadian', 'China');
insert into Locations (lid, city, country) values (97, 'Kertai', 'China');
insert into Locations (lid, city, country) values (98, 'Pingshanhu', 'China');
insert into Locations (lid, city, country) values (99, 'Sarirejo Satu', 'Indonesia');
insert into Locations (lid, city, country) values (100, 'Bulacan', 'Philippines');
insert into Locations (lid, city, country) values (101, 'Ampahana', 'Madagascar');
insert into Locations (lid, city, country) values (102, 'Ilinden', 'Macedonia');
insert into Locations (lid, city, country) values (103, 'Taoyuan', 'China');
insert into Locations (lid, city, country) values (104, 'Gaoqiao', 'China');
insert into Locations (lid, city, country) values (105, 'Mosteiros', 'Portugal');
insert into Locations (lid, city, country) values (106, 'Paghmān', 'Afghanistan');
insert into Locations (lid, city, country) values (107, 'Psychikó', 'Greece');
insert into Locations (lid, city, country) values (108, 'Cové', 'Benin');
insert into Locations (lid, city, country) values (109, 'Kamenka', 'Russia');
insert into Locations (lid, city, country) values (110, 'San Agustin', 'Philippines');
insert into Locations (lid, city, country) values (111, 'Dos Quebradas', 'Colombia');
insert into Locations (lid, city, country) values (112, 'Ayteke Bi', 'Kazakhstan');
insert into Locations (lid, city, country) values (113, 'San Miguel Dueñas', 'Guatemala');
insert into Locations (lid, city, country) values (114, 'Canchaque', 'Peru');
insert into Locations (lid, city, country) values (115, 'Corpus Christi', 'United States');
insert into Locations (lid, city, country) values (116, 'Urbano Noris', 'Cuba');
insert into Locations (lid, city, country) values (117, 'Banjar Bengkelgede', 'Indonesia');
insert into Locations (lid, city, country) values (118, 'Porto-Novo', 'Benin');
insert into Locations (lid, city, country) values (119, 'Stockholm', 'Sweden');
insert into Locations (lid, city, country) values (120, 'Alvaro Obregon', 'Mexico');
insert into Locations (lid, city, country) values (121, 'Nahiyat Ghammas', 'Iraq');
insert into Locations (lid, city, country) values (122, 'Hampang', 'Indonesia');
insert into Locations (lid, city, country) values (123, 'Lenger', 'Kazakhstan');
insert into Locations (lid, city, country) values (124, 'Huanglian', 'China');
insert into Locations (lid, city, country) values (125, 'Calaba', 'Philippines');
insert into Locations (lid, city, country) values (126, 'Palaió Fáliro', 'Greece');
insert into Locations (lid, city, country) values (127, 'Damanhūr', 'Egypt');
insert into Locations (lid, city, country) values (128, 'Santa Teresita', 'Philippines');
insert into Locations (lid, city, country) values (129, 'Genova', 'Italy');
insert into Locations (lid, city, country) values (130, 'Örebro', 'Sweden');
insert into Locations (lid, city, country) values (131, 'Mahaba', 'Philippines');
insert into Locations (lid, city, country) values (132, 'Nytva', 'Russia');
insert into Locations (lid, city, country) values (133, 'Si Mahosot', 'Thailand');
insert into Locations (lid, city, country) values (134, 'Dejilin', 'China');
insert into Locations (lid, city, country) values (135, 'Hong’an Chengguanzhen', 'China');
insert into Locations (lid, city, country) values (136, 'Dikwa', 'Nigeria');
insert into Locations (lid, city, country) values (137, 'Nkongsamba', 'Cameroon');
insert into Locations (lid, city, country) values (138, 'Shuikou', 'China');
insert into Locations (lid, city, country) values (139, 'Rejoso', 'Indonesia');
insert into Locations (lid, city, country) values (140, 'Pau', 'France');
insert into Locations (lid, city, country) values (141, 'Xilanqi', 'China');
insert into Locations (lid, city, country) values (142, 'Krajan Atas Suger Lor', 'Indonesia');
insert into Locations (lid, city, country) values (143, 'Tuguanpu', 'China');
insert into Locations (lid, city, country) values (144, 'Jardín América', 'Argentina');
insert into Locations (lid, city, country) values (145, 'Dunaivtsi', 'Ukraine');
insert into Locations (lid, city, country) values (146, 'Ormož', 'Slovenia');
insert into Locations (lid, city, country) values (147, 'Židlochovice', 'Czech Republic');
insert into Locations (lid, city, country) values (148, 'Noyakert', 'Armenia');
insert into Locations (lid, city, country) values (149, 'Diepsloot', 'South Africa');
insert into Locations (lid, city, country) values (150, 'Ampara', 'Sri Lanka');
insert into Locations (lid, city, country) values (151, 'Votkinsk', 'Russia');
insert into Locations (lid, city, country) values (152, 'Pohang', 'South Korea');
insert into Locations (lid, city, country) values (153, 'Xinmin', 'China');
insert into Locations (lid, city, country) values (154, 'Kilcullen', 'Ireland');
insert into Locations (lid, city, country) values (155, 'Tunggaoen Timur', 'Indonesia');
insert into Locations (lid, city, country) values (156, 'Kalá Déndra', 'Greece');
insert into Locations (lid, city, country) values (157, 'Qarah Bāgh', 'Afghanistan');
insert into Locations (lid, city, country) values (158, 'Huadian', 'China');
insert into Locations (lid, city, country) values (159, 'Rawawilis', 'Indonesia');
insert into Locations (lid, city, country) values (160, 'Millau', 'France');
insert into Locations (lid, city, country) values (161, 'Báguanos', 'Cuba');
insert into Locations (lid, city, country) values (162, 'San Jose', 'Mexico');
insert into Locations (lid, city, country) values (163, 'Atalhada', 'Portugal');
insert into Locations (lid, city, country) values (164, 'Mbaïki', 'Central African Republic');
insert into Locations (lid, city, country) values (165, 'Chishtiān Mandi', 'Pakistan');
insert into Locations (lid, city, country) values (166, 'Two Hills', 'Canada');
insert into Locations (lid, city, country) values (167, 'Sheli', 'China');
insert into Locations (lid, city, country) values (168, 'Chłapowo', 'Poland');
insert into Locations (lid, city, country) values (169, 'Tiedonglu', 'China');
insert into Locations (lid, city, country) values (170, 'Kefar Yona', 'Israel');
insert into Locations (lid, city, country) values (171, 'Xiazhai', 'China');
insert into Locations (lid, city, country) values (172, 'Fangfan', 'China');
insert into Locations (lid, city, country) values (173, 'Infantas', 'Portugal');
insert into Locations (lid, city, country) values (174, 'Beixin', 'China');
insert into Locations (lid, city, country) values (175, 'Stockholm', 'Sweden');
insert into Locations (lid, city, country) values (176, 'Daying', 'China');
insert into Locations (lid, city, country) values (177, 'Anjō', 'Japan');
insert into Locations (lid, city, country) values (178, 'Giyon', 'Ethiopia');
insert into Locations (lid, city, country) values (179, 'Järfälla', 'Sweden');
insert into Locations (lid, city, country) values (180, 'Jatiklampok', 'Indonesia');
insert into Locations (lid, city, country) values (181, 'Sundawenang', 'Indonesia');
insert into Locations (lid, city, country) values (182, 'Daqian', 'China');
insert into Locations (lid, city, country) values (183, 'Mahābād', 'Iran');
insert into Locations (lid, city, country) values (184, 'Perushtitsa', 'Bulgaria');
insert into Locations (lid, city, country) values (185, 'Dagang', 'China');
insert into Locations (lid, city, country) values (186, 'Jardin', 'Mexico');
insert into Locations (lid, city, country) values (187, 'Langzhong', 'China');
insert into Locations (lid, city, country) values (188, 'Shklo', 'Ukraine');
insert into Locations (lid, city, country) values (189, 'Tigbao', 'Philippines');
insert into Locations (lid, city, country) values (190, 'Chikushino-shi', 'Japan');
insert into Locations (lid, city, country) values (191, 'Örebro', 'Sweden');
insert into Locations (lid, city, country) values (192, 'Wangqinzhuang', 'China');
insert into Locations (lid, city, country) values (193, 'Lanlongkou', 'China');
insert into Locations (lid, city, country) values (194, 'Sumber', 'Indonesia');
insert into Locations (lid, city, country) values (195, 'Los Tangos', 'Honduras');
insert into Locations (lid, city, country) values (196, 'Simão Dias', 'Brazil');
insert into Locations (lid, city, country) values (197, 'Mojogajeh', 'Indonesia');
insert into Locations (lid, city, country) values (198, 'White Rock', 'Canada');
insert into Locations (lid, city, country) values (199, 'Mijiang', 'China');
insert into Locations (lid, city, country) values (200, 'Luoyang', 'China');
insert into Locations (lid, city, country) values (201, 'Maracás', 'Brazil');
insert into Locations (lid, city, country) values (202, 'Itō', 'Japan');
insert into Locations (lid, city, country) values (203, 'Kariat Arkmane', 'Morocco');
insert into Locations (lid, city, country) values (204, 'Moosomin', 'Canada');
insert into Locations (lid, city, country) values (205, 'Nueva Loja', 'Ecuador');
insert into Locations (lid, city, country) values (206, 'Ariquemes', 'Brazil');
insert into Locations (lid, city, country) values (207, 'Nuga', 'Mongolia');
insert into Locations (lid, city, country) values (208, 'Sukogunungkrajan', 'Indonesia');
insert into Locations (lid, city, country) values (209, 'Kalodzishchy', 'Belarus');
insert into Locations (lid, city, country) values (210, 'Llauta', 'Peru');
insert into Locations (lid, city, country) values (211, 'Stockholm', 'Sweden');
insert into Locations (lid, city, country) values (212, 'Ülken', 'Kazakhstan');
insert into Locations (lid, city, country) values (213, 'Saint-Étienne', 'France');
insert into Locations (lid, city, country) values (214, 'Lembur Tengah', 'Indonesia');
insert into Locations (lid, city, country) values (215, 'Ulety', 'Russia');
insert into Locations (lid, city, country) values (216, 'Krasnyy Oktyabr’', 'Russia');
insert into Locations (lid, city, country) values (217, 'Arroyito', 'Argentina');
insert into Locations (lid, city, country) values (218, 'Majia', 'China');
insert into Locations (lid, city, country) values (219, 'Gludug', 'Indonesia');
insert into Locations (lid, city, country) values (220, 'Duoxiang', 'China');
insert into Locations (lid, city, country) values (221, 'Khān Neshīn', 'Afghanistan');
insert into Locations (lid, city, country) values (222, 'Guodu', 'China');
insert into Locations (lid, city, country) values (223, 'Zapala', 'Argentina');
insert into Locations (lid, city, country) values (224, 'Szydłowo', 'Poland');
insert into Locations (lid, city, country) values (225, 'Rongdoi', 'China');
insert into Locations (lid, city, country) values (226, 'Serdobsk', 'Russia');
insert into Locations (lid, city, country) values (227, 'Dajt', 'Albania');
insert into Locations (lid, city, country) values (228, 'Budapest', 'Hungary');
insert into Locations (lid, city, country) values (229, 'Albuera', 'Philippines');
insert into Locations (lid, city, country) values (230, 'Pandansari', 'Indonesia');
insert into Locations (lid, city, country) values (231, 'Chonogol', 'Mongolia');
insert into Locations (lid, city, country) values (232, 'Korenëvo', 'Russia');
insert into Locations (lid, city, country) values (233, 'Gingsir', 'Indonesia');
insert into Locations (lid, city, country) values (234, 'Botoh', 'Indonesia');
insert into Locations (lid, city, country) values (235, 'Ryazanskiy', 'Russia');
insert into Locations (lid, city, country) values (236, 'Bessonovka', 'Russia');
insert into Locations (lid, city, country) values (237, 'Długosiodło', 'Poland');
insert into Locations (lid, city, country) values (238, 'Pontevedra', 'Spain');
insert into Locations (lid, city, country) values (239, 'Yaroslavskaya', 'Russia');
insert into Locations (lid, city, country) values (240, 'Yanwan', 'China');
insert into Locations (lid, city, country) values (241, 'Niandou', 'China');
insert into Locations (lid, city, country) values (242, 'Sande Vila Nova', 'Portugal');
insert into Locations (lid, city, country) values (243, 'Mangochi', 'Malawi');
insert into Locations (lid, city, country) values (244, 'Wajir', 'Kenya');
insert into Locations (lid, city, country) values (245, 'Maceo', 'Colombia');
insert into Locations (lid, city, country) values (246, 'Bugana', 'Nigeria');
insert into Locations (lid, city, country) values (247, 'Galis Dua', 'Indonesia');
insert into Locations (lid, city, country) values (248, 'Demir Hisar', 'Macedonia');
insert into Locations (lid, city, country) values (249, 'Sagbayan', 'Philippines');
insert into Locations (lid, city, country) values (250, 'Wangchang', 'China');
insert into Locations (lid, city, country) values (251, 'Ichnya', 'Ukraine');
insert into Locations (lid, city, country) values (252, 'Luzern', 'Switzerland');
insert into Locations (lid, city, country) values (253, 'Muleba', 'Tanzania');
insert into Locations (lid, city, country) values (254, 'Ishigaki', 'Japan');
insert into Locations (lid, city, country) values (255, 'Vozuća', 'Bosnia and Herzegovina');
insert into Locations (lid, city, country) values (256, 'Telbang', 'Philippines');
insert into Locations (lid, city, country) values (257, 'Proletarsk', 'Russia');
insert into Locations (lid, city, country) values (258, 'Yartsevo', 'Russia');
insert into Locations (lid, city, country) values (259, 'Svilengrad', 'Bulgaria');
insert into Locations (lid, city, country) values (260, 'Puolanka', 'Finland');
insert into Locations (lid, city, country) values (261, 'Sambilawang', 'Indonesia');
insert into Locations (lid, city, country) values (262, 'Songon', 'Ivory Coast');
insert into Locations (lid, city, country) values (263, 'Cikaduen', 'Indonesia');
insert into Locations (lid, city, country) values (264, 'Bom Sucesso', 'Portugal');
insert into Locations (lid, city, country) values (265, 'Wanhu', 'China');
insert into Locations (lid, city, country) values (266, 'Balitai', 'China');
insert into Locations (lid, city, country) values (267, 'Malinta', 'Philippines');
insert into Locations (lid, city, country) values (268, 'Jönköping', 'Sweden');
insert into Locations (lid, city, country) values (269, 'Muruy', 'Indonesia');
insert into Locations (lid, city, country) values (270, 'Thị Trấn Yên Thế', 'Vietnam');
insert into Locations (lid, city, country) values (271, 'Krajan Dua Patempuran', 'Indonesia');
insert into Locations (lid, city, country) values (272, 'Yantang', 'China');
insert into Locations (lid, city, country) values (273, 'Xinjie', 'China');
insert into Locations (lid, city, country) values (274, 'Turus', 'Indonesia');
insert into Locations (lid, city, country) values (275, 'Caxarias', 'Portugal');
insert into Locations (lid, city, country) values (276, 'Astara', 'Azerbaijan');
insert into Locations (lid, city, country) values (277, 'Wangkung', 'Indonesia');
insert into Locations (lid, city, country) values (278, 'Baiyin', 'China');
insert into Locations (lid, city, country) values (279, 'Aconibe', 'Equatorial Guinea');
insert into Locations (lid, city, country) values (280, 'Banocboc', 'Philippines');
insert into Locations (lid, city, country) values (281, 'Nuwaybi‘a', 'Egypt');
insert into Locations (lid, city, country) values (282, 'Velika Kladuša', 'Bosnia and Herzegovina');
insert into Locations (lid, city, country) values (283, 'Karjalohja', 'Finland');
insert into Locations (lid, city, country) values (284, 'Tétouan', 'Morocco');
insert into Locations (lid, city, country) values (285, 'Ollantaytambo', 'Peru');
insert into Locations (lid, city, country) values (286, 'Mönchengladbach', 'Germany');
insert into Locations (lid, city, country) values (287, 'Huaicheng', 'China');
insert into Locations (lid, city, country) values (288, 'Peterborough', 'Canada');
insert into Locations (lid, city, country) values (289, 'Ndibène Dahra', 'Senegal');
insert into Locations (lid, city, country) values (290, 'Xiapu', 'China');
insert into Locations (lid, city, country) values (291, 'Baiima', 'Sierra Leone');
insert into Locations (lid, city, country) values (292, 'Loja', 'Ecuador');
insert into Locations (lid, city, country) values (293, 'Taesal-li', 'South Korea');
insert into Locations (lid, city, country) values (294, 'Đồi Ngô', 'Vietnam');
insert into Locations (lid, city, country) values (295, 'San Pedro Necta', 'Guatemala');
insert into Locations (lid, city, country) values (296, 'Huangjin', 'China');
insert into Locations (lid, city, country) values (297, 'Magepanda', 'Indonesia');
insert into Locations (lid, city, country) values (298, 'Nakajah', 'Indonesia');
insert into Locations (lid, city, country) values (299, 'Sidem', 'Indonesia');
insert into Locations (lid, city, country) values (300, 'Pylaía', 'Greece');
insert into Locations (lid, city, country) values (301, 'East Angus', 'Canada');
insert into Locations (lid, city, country) values (302, 'Hakodate', 'Japan');
insert into Locations (lid, city, country) values (303, 'Horred', 'Sweden');
insert into Locations (lid, city, country) values (304, 'Ust’-Koksa', 'Russia');
insert into Locations (lid, city, country) values (305, 'Dong Charoen', 'Thailand');
insert into Locations (lid, city, country) values (306, 'Eslöv', 'Sweden');
insert into Locations (lid, city, country) values (307, 'Lüfeng', 'China');
insert into Locations (lid, city, country) values (308, 'Łeba', 'Poland');
insert into Locations (lid, city, country) values (309, 'Huaxijie', 'China');
insert into Locations (lid, city, country) values (310, 'Antagan Segunda', 'Philippines');
insert into Locations (lid, city, country) values (311, 'Rosso', 'Mauritania');
insert into Locations (lid, city, country) values (312, 'Wunat', 'Indonesia');
insert into Locations (lid, city, country) values (313, 'Las Varas', 'Argentina');
insert into Locations (lid, city, country) values (314, 'Tikiw', 'Philippines');
insert into Locations (lid, city, country) values (315, 'Doyong', 'Philippines');
insert into Locations (lid, city, country) values (316, 'El Viejo', 'Nicaragua');
insert into Locations (lid, city, country) values (317, 'Žďár nad Sázavou Druhy', 'Czech Republic');
insert into Locations (lid, city, country) values (318, 'Ulaan-Uul', 'Mongolia');
insert into Locations (lid, city, country) values (319, 'Garhi Khairo', 'Pakistan');
insert into Locations (lid, city, country) values (320, 'Borek', 'Poland');
insert into Locations (lid, city, country) values (321, 'Biru', 'China');
insert into Locations (lid, city, country) values (322, 'Smārde', 'Latvia');
insert into Locations (lid, city, country) values (323, 'Bor', 'Serbia');
insert into Locations (lid, city, country) values (324, 'Siennica Różana', 'Poland');
insert into Locations (lid, city, country) values (325, 'Victoria', 'Argentina');
insert into Locations (lid, city, country) values (326, 'Srednebelaya', 'Russia');
insert into Locations (lid, city, country) values (327, 'Chengyang', 'China');
insert into Locations (lid, city, country) values (328, 'Pianbai', 'China');
insert into Locations (lid, city, country) values (329, 'Darwin', 'Argentina');
insert into Locations (lid, city, country) values (330, 'Oumiao', 'China');
insert into Locations (lid, city, country) values (331, 'Zhongzuiling', 'China');
insert into Locations (lid, city, country) values (332, 'Enriquillo', 'Dominican Republic');
insert into Locations (lid, city, country) values (333, 'Ölgiy', 'Mongolia');
insert into Locations (lid, city, country) values (334, 'Kaminoyama', 'Japan');
insert into Locations (lid, city, country) values (335, 'Al Khārijah', 'Egypt');
insert into Locations (lid, city, country) values (336, 'Santa Cruz', 'Philippines');
insert into Locations (lid, city, country) values (337, 'Artur Nogueira', 'Brazil');
insert into Locations (lid, city, country) values (338, 'Cachoeira do Sul', 'Brazil');
insert into Locations (lid, city, country) values (339, 'Mariquita', 'Colombia');
insert into Locations (lid, city, country) values (340, 'Khlong Hat', 'Thailand');
insert into Locations (lid, city, country) values (341, 'Medvedovskaya', 'Russia');
insert into Locations (lid, city, country) values (342, 'Kalávryta', 'Greece');
insert into Locations (lid, city, country) values (343, 'Chenfang', 'China');
insert into Locations (lid, city, country) values (344, 'Orocué', 'Colombia');
insert into Locations (lid, city, country) values (345, 'Malartic', 'Canada');
insert into Locations (lid, city, country) values (346, 'Pataias', 'Portugal');
insert into Locations (lid, city, country) values (347, 'Kota Kinabalu', 'Malaysia');
insert into Locations (lid, city, country) values (348, 'Futian', 'China');
insert into Locations (lid, city, country) values (349, 'Bello', 'Colombia');
insert into Locations (lid, city, country) values (350, 'Onzaga', 'Colombia');
insert into Locations (lid, city, country) values (351, 'Bamencheng', 'China');
insert into Locations (lid, city, country) values (352, 'Sanshui', 'China');
insert into Locations (lid, city, country) values (353, 'Sukaharja', 'Indonesia');
insert into Locations (lid, city, country) values (354, 'Kota Bharu', 'Malaysia');
insert into Locations (lid, city, country) values (355, 'Yinghai', 'China');
insert into Locations (lid, city, country) values (356, 'Agkathiá', 'Greece');
insert into Locations (lid, city, country) values (357, 'Bagong Pagasa', 'Philippines');
insert into Locations (lid, city, country) values (358, 'Cekcyn', 'Poland');
insert into Locations (lid, city, country) values (359, 'Mhango', 'Tanzania');
insert into Locations (lid, city, country) values (360, 'Luleå', 'Sweden');
insert into Locations (lid, city, country) values (361, 'Borzna', 'Ukraine');
insert into Locations (lid, city, country) values (362, 'Gonzalo', 'Dominican Republic');
insert into Locations (lid, city, country) values (363, 'Xomong', 'China');
insert into Locations (lid, city, country) values (364, 'Bërxull', 'Albania');
insert into Locations (lid, city, country) values (365, 'Sumbe', 'Angola');
insert into Locations (lid, city, country) values (366, 'San Andrés', 'Guatemala');
insert into Locations (lid, city, country) values (367, 'Batuan', 'China');
insert into Locations (lid, city, country) values (368, 'Danbury', 'United States');
insert into Locations (lid, city, country) values (369, 'Turochak', 'Russia');
insert into Locations (lid, city, country) values (370, 'Homagama', 'Sri Lanka');
insert into Locations (lid, city, country) values (371, 'Solna', 'Sweden');
insert into Locations (lid, city, country) values (372, 'Villa Lugano', 'Argentina');
insert into Locations (lid, city, country) values (373, 'Thepharak', 'Thailand');
insert into Locations (lid, city, country) values (374, 'Gajrug', 'Indonesia');
insert into Locations (lid, city, country) values (375, 'San Miguel del Padrón', 'Cuba');
insert into Locations (lid, city, country) values (376, 'Mosjøen', 'Norway');
insert into Locations (lid, city, country) values (377, 'Mthatha', 'South Africa');
insert into Locations (lid, city, country) values (378, 'Weepanapi', 'Indonesia');
insert into Locations (lid, city, country) values (379, 'Cavan', 'Ireland');
insert into Locations (lid, city, country) values (380, 'El Playón', 'Colombia');
insert into Locations (lid, city, country) values (381, 'Ipoh', 'Malaysia');
insert into Locations (lid, city, country) values (382, 'Wenceslau Braz', 'Brazil');
insert into Locations (lid, city, country) values (383, 'Saint-Quentin-en-Yvelines', 'France');
insert into Locations (lid, city, country) values (384, 'Söderköping', 'Sweden');
insert into Locations (lid, city, country) values (385, 'Orléans', 'France');
insert into Locations (lid, city, country) values (386, 'Luanshya', 'Zambia');
insert into Locations (lid, city, country) values (387, 'Tierra y Libertad', 'Mexico');
insert into Locations (lid, city, country) values (388, 'Wojnicz', 'Poland');
insert into Locations (lid, city, country) values (389, 'Sobo', 'Indonesia');
insert into Locations (lid, city, country) values (390, 'Levoberezhnaya', 'Russia');
insert into Locations (lid, city, country) values (391, 'Yerevan', 'Armenia');
insert into Locations (lid, city, country) values (392, 'San Pedro', 'Mexico');
insert into Locations (lid, city, country) values (393, 'Novodmitriyevskaya', 'Russia');
insert into Locations (lid, city, country) values (394, 'Saryg-Sep', 'Russia');
insert into Locations (lid, city, country) values (395, 'Tanbu', 'China');
insert into Locations (lid, city, country) values (396, 'Shūkat aş Şūfī', 'Palestinian Territory');
insert into Locations (lid, city, country) values (397, 'Fatufeto', 'Indonesia');
insert into Locations (lid, city, country) values (398, 'Gémeos', 'Portugal');
insert into Locations (lid, city, country) values (399, 'Bacungan', 'Philippines');
insert into Locations (lid, city, country) values (400, 'Tutong', 'Brunei');
insert into Locations (lid, city, country) values (401, 'Aime', 'France');
insert into Locations (lid, city, country) values (402, 'Čeladná', 'Czech Republic');
insert into Locations (lid, city, country) values (403, 'Sanjiazi', 'China');
insert into Locations (lid, city, country) values (404, 'Zhangbei', 'China');
insert into Locations (lid, city, country) values (405, 'Yogyakarta', 'Indonesia');
insert into Locations (lid, city, country) values (406, 'Lanhas', 'Portugal');
insert into Locations (lid, city, country) values (407, 'Kacha', 'Ukraine');
insert into Locations (lid, city, country) values (408, 'Qishui', 'China');
insert into Locations (lid, city, country) values (409, 'Norrköping', 'Sweden');
insert into Locations (lid, city, country) values (410, 'Rio Branco do Sul', 'Brazil');
insert into Locations (lid, city, country) values (411, 'Nanqiu', 'China');
insert into Locations (lid, city, country) values (412, 'Vilarinho', 'Portugal');
insert into Locations (lid, city, country) values (413, 'Naju', 'South Korea');
insert into Locations (lid, city, country) values (414, 'Dedza', 'Malawi');
insert into Locations (lid, city, country) values (415, 'Dolna Banjica', 'Macedonia');
insert into Locations (lid, city, country) values (416, 'Lewograran', 'Indonesia');
insert into Locations (lid, city, country) values (417, 'Göteborg', 'Sweden');
insert into Locations (lid, city, country) values (418, 'Dologon', 'Philippines');
insert into Locations (lid, city, country) values (419, 'Sv. Trojica v Slov. Goricah', 'Slovenia');
insert into Locations (lid, city, country) values (420, 'Sar-e Pul', 'Afghanistan');
insert into Locations (lid, city, country) values (421, 'Yara', 'Cuba');
insert into Locations (lid, city, country) values (422, 'Changchuan', 'China');
insert into Locations (lid, city, country) values (423, 'Coxim', 'Brazil');
insert into Locations (lid, city, country) values (424, 'Périgueux', 'France');
insert into Locations (lid, city, country) values (425, 'Xiaochi', 'China');
insert into Locations (lid, city, country) values (426, 'Tierra y Libertad', 'Mexico');
insert into Locations (lid, city, country) values (427, 'Voorburg', 'Netherlands');
insert into Locations (lid, city, country) values (428, 'Rudnogorsk', 'Russia');
insert into Locations (lid, city, country) values (429, 'Quwaysinā', 'Egypt');
insert into Locations (lid, city, country) values (430, 'Bajiao', 'China');
insert into Locations (lid, city, country) values (431, 'Parthenay', 'France');
insert into Locations (lid, city, country) values (432, 'Xiancun', 'China');
insert into Locations (lid, city, country) values (433, 'Oued Lill', 'Tunisia');
insert into Locations (lid, city, country) values (434, 'Nesebar', 'Bulgaria');
insert into Locations (lid, city, country) values (435, 'Krajan Dua Patempuran', 'Indonesia');
insert into Locations (lid, city, country) values (436, 'Bouillon', 'Belgium');
insert into Locations (lid, city, country) values (437, 'Daxing', 'China');
insert into Locations (lid, city, country) values (438, 'Al Bilād', 'Yemen');
insert into Locations (lid, city, country) values (439, 'Jiusi', 'China');
insert into Locations (lid, city, country) values (440, 'Hengtang', 'China');
insert into Locations (lid, city, country) values (441, 'Pandan Niog', 'Philippines');
insert into Locations (lid, city, country) values (442, 'Ljusdal', 'Sweden');
insert into Locations (lid, city, country) values (443, 'Dori', 'Burkina Faso');
insert into Locations (lid, city, country) values (444, 'Ishinomaki', 'Japan');
insert into Locations (lid, city, country) values (445, 'Kítsi', 'Greece');
insert into Locations (lid, city, country) values (446, 'Maïné Soroa', 'Niger');
insert into Locations (lid, city, country) values (447, '‘Anjarah', 'Jordan');
insert into Locations (lid, city, country) values (448, 'Orekhovo-Borisovo', 'Russia');
insert into Locations (lid, city, country) values (449, 'Los Angeles', 'United States');
insert into Locations (lid, city, country) values (450, 'Pantai', 'Indonesia');
insert into Locations (lid, city, country) values (451, 'Dabou', 'Ivory Coast');
insert into Locations (lid, city, country) values (452, 'Baoxing', 'China');
insert into Locations (lid, city, country) values (453, 'Cicheng', 'China');
insert into Locations (lid, city, country) values (454, 'Jiangchuanlu', 'China');
insert into Locations (lid, city, country) values (455, 'Panyam', 'Nigeria');
insert into Locations (lid, city, country) values (456, 'Huanglong', 'China');
insert into Locations (lid, city, country) values (457, 'Lumbatan', 'Philippines');
insert into Locations (lid, city, country) values (458, 'Topeka', 'United States');
insert into Locations (lid, city, country) values (459, 'Duekoué', 'Ivory Coast');
insert into Locations (lid, city, country) values (460, 'Nanyang', 'China');
insert into Locations (lid, city, country) values (461, 'Sharga', 'Mongolia');
insert into Locations (lid, city, country) values (462, 'Karlstad', 'Sweden');
insert into Locations (lid, city, country) values (463, 'Sidamukti', 'Indonesia');
insert into Locations (lid, city, country) values (464, 'Alto de São Sebastião', 'Portugal');
insert into Locations (lid, city, country) values (465, 'Menghe', 'China');
insert into Locations (lid, city, country) values (466, 'Liupai', 'China');
insert into Locations (lid, city, country) values (467, 'Dunhou', 'China');
insert into Locations (lid, city, country) values (468, 'Azurva', 'Portugal');
insert into Locations (lid, city, country) values (469, 'Boynton Beach', 'United States');
insert into Locations (lid, city, country) values (470, 'Agua Fría', 'Honduras');
insert into Locations (lid, city, country) values (471, 'Wilków', 'Poland');
insert into Locations (lid, city, country) values (472, 'Bystra', 'Poland');
insert into Locations (lid, city, country) values (473, 'Khasht’arrak', 'Armenia');
insert into Locations (lid, city, country) values (474, 'Anin', 'Indonesia');
insert into Locations (lid, city, country) values (475, 'Zhuangbu', 'China');
insert into Locations (lid, city, country) values (476, 'Fort Worth', 'United States');
insert into Locations (lid, city, country) values (477, 'Huandiqiao', 'China');
insert into Locations (lid, city, country) values (478, 'Lutomiersk', 'Poland');
insert into Locations (lid, city, country) values (479, 'Vichadero', 'Uruguay');
insert into Locations (lid, city, country) values (480, 'Dalarik', 'Armenia');
insert into Locations (lid, city, country) values (481, 'Radomir', 'Bulgaria');
insert into Locations (lid, city, country) values (482, 'Sulahan', 'Indonesia');
insert into Locations (lid, city, country) values (483, 'Zvishavane', 'Zimbabwe');
insert into Locations (lid, city, country) values (484, 'Tambo', 'Philippines');
insert into Locations (lid, city, country) values (485, 'Siwalan', 'Indonesia');
insert into Locations (lid, city, country) values (486, 'Krajan Satu', 'Indonesia');
insert into Locations (lid, city, country) values (487, 'Bromma', 'Sweden');
insert into Locations (lid, city, country) values (488, 'Maqian', 'China');
insert into Locations (lid, city, country) values (489, 'Yonghe', 'China');
insert into Locations (lid, city, country) values (490, 'Hagfors', 'Sweden');
insert into Locations (lid, city, country) values (491, 'Augusta', 'United States');
insert into Locations (lid, city, country) values (492, 'Ryczów', 'Poland');
insert into Locations (lid, city, country) values (493, 'Gabao', 'Philippines');
insert into Locations (lid, city, country) values (494, 'Djohong', 'Cameroon');
insert into Locations (lid, city, country) values (495, 'Чучер - Сандево', 'Macedonia');
insert into Locations (lid, city, country) values (496, 'Lidzbark', 'Poland');
insert into Locations (lid, city, country) values (497, 'Dorūd', 'Iran');
insert into Locations (lid, city, country) values (498, 'Wulan Hada', 'China');
insert into Locations (lid, city, country) values (499, 'Banjar Penyalin', 'Indonesia');
insert into Locations (lid, city, country) values (500, 'Osypenko', 'Ukraine');
insert into Locations (lid, city, country) values (501, 'Piedras', 'Colombia');
insert into Locations (lid, city, country) values (502, 'Guayabo Dulce', 'Dominican Republic');
insert into Locations (lid, city, country) values (503, 'Nantes', 'France');
insert into Locations (lid, city, country) values (504, 'Yiliu', 'China');
insert into Locations (lid, city, country) values (505, 'Louisville', 'United States');
insert into Locations (lid, city, country) values (506, 'Strellc i Epërm', 'Kosovo');
insert into Locations (lid, city, country) values (507, 'Ban Thai Tan', 'Thailand');
insert into Locations (lid, city, country) values (508, 'Saint John', 'Malta');
insert into Locations (lid, city, country) values (509, 'Caramay', 'Philippines');
insert into Locations (lid, city, country) values (510, 'Jingdu', 'China');
insert into Locations (lid, city, country) values (511, 'Itagibá', 'Brazil');
insert into Locations (lid, city, country) values (512, 'Reda', 'Poland');
insert into Locations (lid, city, country) values (513, 'Bohumín', 'Czech Republic');
insert into Locations (lid, city, country) values (514, 'Contraalmirante Cordero', 'Argentina');
insert into Locations (lid, city, country) values (515, 'Oguta', 'Nigeria');
insert into Locations (lid, city, country) values (516, 'Xibin', 'China');
insert into Locations (lid, city, country) values (517, 'Santiago del Estero', 'Argentina');
insert into Locations (lid, city, country) values (518, 'Guohua', 'China');
insert into Locations (lid, city, country) values (519, 'Topi', 'Pakistan');
insert into Locations (lid, city, country) values (520, 'Pingxiang', 'China');
insert into Locations (lid, city, country) values (521, 'Manuel Antonio Mesones Muro', 'Peru');
insert into Locations (lid, city, country) values (522, 'Bailuquan', 'China');
insert into Locations (lid, city, country) values (523, 'Tallaght', 'Ireland');
insert into Locations (lid, city, country) values (524, 'Alexandroúpoli', 'Greece');
insert into Locations (lid, city, country) values (525, 'Thị Trấn Quán Lào', 'Vietnam');
insert into Locations (lid, city, country) values (526, 'Sātkania', 'Bangladesh');
insert into Locations (lid, city, country) values (527, 'Al Ghizlānīyah', 'Syria');
insert into Locations (lid, city, country) values (528, 'Lagoa Santa', 'Brazil');
insert into Locations (lid, city, country) values (529, 'Rio Covo', 'Portugal');
insert into Locations (lid, city, country) values (530, 'Zavolzh’ye', 'Russia');
insert into Locations (lid, city, country) values (531, 'Zhendong', 'China');
insert into Locations (lid, city, country) values (532, 'Clermont-Ferrand', 'France');
insert into Locations (lid, city, country) values (533, 'Vicuña Mackenna', 'Argentina');
insert into Locations (lid, city, country) values (534, 'Wonodadi', 'Indonesia');
insert into Locations (lid, city, country) values (535, 'Krasnomayskiy', 'Russia');
insert into Locations (lid, city, country) values (536, 'Ampasimanolotra', 'Madagascar');
insert into Locations (lid, city, country) values (537, 'Danao', 'Philippines');
insert into Locations (lid, city, country) values (538, 'Kebunkelapa', 'Indonesia');
insert into Locations (lid, city, country) values (539, 'Patenongan', 'Indonesia');
insert into Locations (lid, city, country) values (540, 'Laguilayan', 'Philippines');
insert into Locations (lid, city, country) values (541, 'Tola', 'Nicaragua');
insert into Locations (lid, city, country) values (542, 'Cruzeiro do Oeste', 'Brazil');
insert into Locations (lid, city, country) values (543, 'Bang Bo', 'Thailand');
insert into Locations (lid, city, country) values (544, 'Saskatoon', 'Canada');
insert into Locations (lid, city, country) values (545, 'Thị Trấn Quảng Uyên', 'Vietnam');
insert into Locations (lid, city, country) values (546, 'Kadugannawa', 'Sri Lanka');
insert into Locations (lid, city, country) values (547, 'Glubokiy', 'Russia');
insert into Locations (lid, city, country) values (548, 'Zainsk', 'Russia');
insert into Locations (lid, city, country) values (549, 'El Paraiso', 'Mexico');
insert into Locations (lid, city, country) values (550, 'Uttar Char Fasson', 'Bangladesh');
insert into Locations (lid, city, country) values (551, 'Vlissingen', 'Netherlands');
insert into Locations (lid, city, country) values (552, 'Köln', 'Germany');
insert into Locations (lid, city, country) values (553, 'Zdiby', 'Czech Republic');
insert into Locations (lid, city, country) values (554, 'Valence', 'France');
insert into Locations (lid, city, country) values (555, 'Kowala', 'Poland');
insert into Locations (lid, city, country) values (556, 'Nancheng', 'China');
insert into Locations (lid, city, country) values (557, 'Sandakan', 'Malaysia');
insert into Locations (lid, city, country) values (558, 'Genyem', 'Indonesia');
insert into Locations (lid, city, country) values (559, 'Mādabā', 'Jordan');
insert into Locations (lid, city, country) values (560, 'Chwaszczyno', 'Poland');
insert into Locations (lid, city, country) values (561, 'Pakisrejo', 'Indonesia');
insert into Locations (lid, city, country) values (562, 'Miringa', 'Nigeria');
insert into Locations (lid, city, country) values (563, 'Sakassou', 'Ivory Coast');
insert into Locations (lid, city, country) values (564, 'Adámas', 'Greece');
insert into Locations (lid, city, country) values (565, 'Panggungrejo', 'Indonesia');
insert into Locations (lid, city, country) values (566, 'Gongli', 'China');
insert into Locations (lid, city, country) values (567, 'Yarīm', 'Yemen');
insert into Locations (lid, city, country) values (568, 'Padangtiji', 'Indonesia');
insert into Locations (lid, city, country) values (569, 'Lewoeleng', 'Indonesia');
insert into Locations (lid, city, country) values (570, 'Ibagué', 'Colombia');
insert into Locations (lid, city, country) values (571, 'Panayagan', 'Indonesia');
insert into Locations (lid, city, country) values (572, 'Maebashi-shi', 'Japan');
insert into Locations (lid, city, country) values (573, 'Dajianchang', 'China');
insert into Locations (lid, city, country) values (574, 'Gucheng', 'China');
insert into Locations (lid, city, country) values (575, 'Daxing', 'China');
insert into Locations (lid, city, country) values (576, 'Gadžin Han', 'Serbia');
insert into Locations (lid, city, country) values (577, 'Pasirhaur', 'Indonesia');
insert into Locations (lid, city, country) values (578, 'Banawang', 'Philippines');
insert into Locations (lid, city, country) values (579, 'Tasikona', 'Indonesia');
insert into Locations (lid, city, country) values (580, 'Genisséa', 'Greece');
insert into Locations (lid, city, country) values (581, 'Ágios Andréas', 'Greece');
insert into Locations (lid, city, country) values (582, 'Ibara', 'Japan');
insert into Locations (lid, city, country) values (583, 'Xinxu', 'China');
insert into Locations (lid, city, country) values (584, 'Ayang-ni', 'North Korea');
insert into Locations (lid, city, country) values (585, 'Loma', 'Sierra Leone');
insert into Locations (lid, city, country) values (586, 'Santa Maria da Vitória', 'Brazil');
insert into Locations (lid, city, country) values (587, 'Yangba', 'China');
insert into Locations (lid, city, country) values (588, 'Banho e Carvalhosa', 'Portugal');
insert into Locations (lid, city, country) values (589, 'Ash Shawātī', 'Yemen');
insert into Locations (lid, city, country) values (590, 'Muaraenim', 'Indonesia');
insert into Locations (lid, city, country) values (591, 'Uba', 'Nigeria');
insert into Locations (lid, city, country) values (592, 'Tete', 'Mozambique');
insert into Locations (lid, city, country) values (593, 'Nedryhayliv', 'Ukraine');
insert into Locations (lid, city, country) values (594, 'Qiandong', 'China');
insert into Locations (lid, city, country) values (595, 'Thị Trấn Quảng Uyên', 'Vietnam');
insert into Locations (lid, city, country) values (596, 'Pilchowice', 'Poland');
insert into Locations (lid, city, country) values (597, 'Pangal Sur', 'Philippines');
insert into Locations (lid, city, country) values (598, 'Hrvatini', 'Slovenia');
insert into Locations (lid, city, country) values (599, 'Cirangrang', 'Indonesia');
insert into Locations (lid, city, country) values (600, 'Gulai', 'China');
insert into Locations (lid, city, country) values (601, 'Peicheng', 'China');
insert into Locations (lid, city, country) values (602, 'Meizhou', 'China');
insert into Locations (lid, city, country) values (603, 'Culeng', 'Indonesia');
insert into Locations (lid, city, country) values (604, 'Jingyang', 'China');
insert into Locations (lid, city, country) values (605, 'Dembéni', 'Comoros');
insert into Locations (lid, city, country) values (606, 'São Paio de Gramaços', 'Portugal');
insert into Locations (lid, city, country) values (607, 'Gagarin', 'Uzbekistan');
insert into Locations (lid, city, country) values (608, 'Zhaxi', 'China');
insert into Locations (lid, city, country) values (609, 'Ash Shuqayrah', 'Yemen');
insert into Locations (lid, city, country) values (610, 'Tarkastad', 'South Africa');
insert into Locations (lid, city, country) values (611, 'Tršić', 'Serbia');
insert into Locations (lid, city, country) values (612, 'Nongba', 'China');
insert into Locations (lid, city, country) values (613, 'Nanyang', 'China');
insert into Locations (lid, city, country) values (614, 'Vohibinany', 'Madagascar');
insert into Locations (lid, city, country) values (615, 'Primorsk', 'Russia');
insert into Locations (lid, city, country) values (616, 'Beutong Ateuh', 'Indonesia');
insert into Locations (lid, city, country) values (617, 'Muzhou', 'China');
insert into Locations (lid, city, country) values (618, 'Bergem', 'Luxembourg');
insert into Locations (lid, city, country) values (619, 'Luan Balu', 'Indonesia');
insert into Locations (lid, city, country) values (620, 'Nam Kliang', 'Thailand');
insert into Locations (lid, city, country) values (621, 'Yunxiang', 'China');
insert into Locations (lid, city, country) values (622, 'Long Xuyên', 'Vietnam');
insert into Locations (lid, city, country) values (623, 'Wang Yang', 'Thailand');
insert into Locations (lid, city, country) values (624, 'La Mohammedia', 'Tunisia');
insert into Locations (lid, city, country) values (625, 'Eiguliai', 'Lithuania');
insert into Locations (lid, city, country) values (626, 'Yanda Bayo', 'Nigeria');
insert into Locations (lid, city, country) values (627, 'Itapetinga', 'Brazil');
insert into Locations (lid, city, country) values (628, 'Xiangzhou', 'China');
insert into Locations (lid, city, country) values (629, 'Muarabuliti', 'Indonesia');
insert into Locations (lid, city, country) values (630, 'Neiguan', 'China');
insert into Locations (lid, city, country) values (631, 'Halimpu', 'Indonesia');
insert into Locations (lid, city, country) values (632, 'Qaffīn', 'Palestinian Territory');
insert into Locations (lid, city, country) values (633, 'Breia', 'Portugal');
insert into Locations (lid, city, country) values (634, 'Weibin', 'China');
insert into Locations (lid, city, country) values (635, 'Ban Haet', 'Thailand');
insert into Locations (lid, city, country) values (636, 'Byczyna', 'Poland');
insert into Locations (lid, city, country) values (637, 'Ponjen', 'Indonesia');
insert into Locations (lid, city, country) values (638, 'Thul', 'Pakistan');
insert into Locations (lid, city, country) values (639, 'Tempe', 'United States');
insert into Locations (lid, city, country) values (640, 'Faīẕābād', 'Afghanistan');
insert into Locations (lid, city, country) values (641, 'Hondo Valle', 'Dominican Republic');
insert into Locations (lid, city, country) values (642, 'Junshan', 'China');
insert into Locations (lid, city, country) values (643, 'Hats’avan', 'Armenia');
insert into Locations (lid, city, country) values (644, 'Kiel', 'Germany');
insert into Locations (lid, city, country) values (645, 'Paagahan', 'Philippines');
insert into Locations (lid, city, country) values (646, 'Laveiras', 'Portugal');
insert into Locations (lid, city, country) values (647, 'Lanjaghbyur', 'Armenia');
insert into Locations (lid, city, country) values (648, 'Cambebba', 'Brazil');
insert into Locations (lid, city, country) values (649, 'Vincennes', 'France');
insert into Locations (lid, city, country) values (650, 'Krzczonów', 'Poland');
insert into Locations (lid, city, country) values (651, 'Chishmy', 'Russia');
insert into Locations (lid, city, country) values (652, 'Phatthalung', 'Thailand');
insert into Locations (lid, city, country) values (653, 'Noeltoko', 'Indonesia');
insert into Locations (lid, city, country) values (654, 'Żabieniec', 'Poland');
insert into Locations (lid, city, country) values (655, 'Cacequi', 'Brazil');
insert into Locations (lid, city, country) values (656, 'Rambouillet', 'France');
insert into Locations (lid, city, country) values (657, 'Raczki', 'Poland');
insert into Locations (lid, city, country) values (658, 'Intipucá', 'El Salvador');
insert into Locations (lid, city, country) values (659, 'Lacdayan', 'Philippines');
insert into Locations (lid, city, country) values (660, 'Karak City', 'Jordan');
insert into Locations (lid, city, country) values (661, 'Sidomulyo', 'Indonesia');
insert into Locations (lid, city, country) values (662, 'Sukojember', 'Indonesia');
insert into Locations (lid, city, country) values (663, 'Yuanyang Zhen', 'China');
insert into Locations (lid, city, country) values (664, 'Kuala Lumpur', 'Malaysia');
insert into Locations (lid, city, country) values (665, 'Barice', 'Bosnia and Herzegovina');
insert into Locations (lid, city, country) values (666, 'Yurino', 'Russia');
insert into Locations (lid, city, country) values (667, 'Grazhdanka', 'Russia');
insert into Locations (lid, city, country) values (668, 'San Pedro de Ycuamandiyú', 'Paraguay');
insert into Locations (lid, city, country) values (669, 'Baliuag', 'Philippines');
insert into Locations (lid, city, country) values (670, 'Santa Cruz', 'Honduras');
insert into Locations (lid, city, country) values (671, 'Maksatikha', 'Russia');
insert into Locations (lid, city, country) values (672, 'Gotemba', 'Japan');
insert into Locations (lid, city, country) values (673, 'Pak Chong', 'Thailand');
insert into Locations (lid, city, country) values (674, 'Rosario', 'Philippines');
insert into Locations (lid, city, country) values (675, 'Piotrków Kujawski', 'Poland');
insert into Locations (lid, city, country) values (676, 'Al Bawīţī', 'Egypt');
insert into Locations (lid, city, country) values (677, 'Kavajë', 'Albania');
insert into Locations (lid, city, country) values (678, 'Bulongji', 'China');
insert into Locations (lid, city, country) values (679, 'Busia', 'Kenya');
insert into Locations (lid, city, country) values (680, 'Cihambali', 'Indonesia');
insert into Locations (lid, city, country) values (681, 'Huo’erqi', 'China');
insert into Locations (lid, city, country) values (682, 'Zlatar', 'Croatia');
insert into Locations (lid, city, country) values (683, 'Ḩajjah', 'Yemen');
insert into Locations (lid, city, country) values (684, 'Samashki', 'Russia');
insert into Locations (lid, city, country) values (685, 'Trilj', 'Croatia');
insert into Locations (lid, city, country) values (686, 'Laval', 'France');
insert into Locations (lid, city, country) values (687, 'Mekarsari', 'Indonesia');
insert into Locations (lid, city, country) values (688, 'Dobryanka', 'Russia');
insert into Locations (lid, city, country) values (689, 'Budapest', 'Hungary');
insert into Locations (lid, city, country) values (690, 'São Miguel do Iguaçu', 'Brazil');
insert into Locations (lid, city, country) values (691, 'Desa Gegempalan', 'Indonesia');
insert into Locations (lid, city, country) values (692, 'Poá', 'Brazil');
insert into Locations (lid, city, country) values (693, 'Pretana', 'Indonesia');
insert into Locations (lid, city, country) values (694, 'Dharān Bāzār', 'Nepal');
insert into Locations (lid, city, country) values (695, 'Dongbian', 'China');
insert into Locations (lid, city, country) values (696, 'Mondim de Basto', 'Portugal');
insert into Locations (lid, city, country) values (697, 'Itaitinga', 'Brazil');
insert into Locations (lid, city, country) values (698, 'Georgīevka', 'Kazakhstan');
insert into Locations (lid, city, country) values (699, 'Pianbai', 'China');
insert into Locations (lid, city, country) values (700, 'Llacanora', 'Peru');
insert into Locations (lid, city, country) values (701, 'Bački Breg', 'Serbia');
insert into Locations (lid, city, country) values (702, 'Saltsjö-Boo', 'Sweden');
insert into Locations (lid, city, country) values (703, 'Carvalhal', 'Portugal');
insert into Locations (lid, city, country) values (704, 'Oematnunu', 'Indonesia');
insert into Locations (lid, city, country) values (705, 'Colón', 'Panama');
insert into Locations (lid, city, country) values (706, 'Paraguaçu', 'Brazil');
insert into Locations (lid, city, country) values (707, 'Yangjiao', 'China');
insert into Locations (lid, city, country) values (708, 'Nowa Ruda', 'Poland');
insert into Locations (lid, city, country) values (709, 'Andalucía', 'Colombia');
insert into Locations (lid, city, country) values (710, 'Weitian', 'China');
insert into Locations (lid, city, country) values (711, 'Toyonaka', 'Japan');
insert into Locations (lid, city, country) values (712, 'Kyenjojo', 'Uganda');
insert into Locations (lid, city, country) values (713, 'Septfontaines', 'Luxembourg');
insert into Locations (lid, city, country) values (714, 'Karangsari', 'Indonesia');
insert into Locations (lid, city, country) values (715, 'Hostivice', 'Czech Republic');
insert into Locations (lid, city, country) values (716, 'Gumaus', 'Philippines');
insert into Locations (lid, city, country) values (717, 'Kowale', 'Poland');
insert into Locations (lid, city, country) values (718, 'Rejoso', 'Indonesia');
insert into Locations (lid, city, country) values (719, 'San José de Colinas', 'Honduras');
insert into Locations (lid, city, country) values (720, 'Pavlogradka', 'Russia');
insert into Locations (lid, city, country) values (721, 'Topeka', 'United States');
insert into Locations (lid, city, country) values (722, 'San Patricio', 'Paraguay');
insert into Locations (lid, city, country) values (723, 'Fundación', 'Dominican Republic');
insert into Locations (lid, city, country) values (724, 'Wailang', 'China');
insert into Locations (lid, city, country) values (725, 'Panggunguni', 'Indonesia');
insert into Locations (lid, city, country) values (726, 'Jamundí', 'Colombia');
insert into Locations (lid, city, country) values (727, 'Thanh Ba', 'Vietnam');
insert into Locations (lid, city, country) values (728, 'Nesebar', 'Bulgaria');
insert into Locations (lid, city, country) values (729, 'Ngetkib', 'Palau');
insert into Locations (lid, city, country) values (730, 'Quwaysinā', 'Egypt');
insert into Locations (lid, city, country) values (731, 'Igaraçu do Tietê', 'Brazil');
insert into Locations (lid, city, country) values (732, 'Xinglong', 'China');
insert into Locations (lid, city, country) values (733, 'Bangkal', 'Indonesia');
insert into Locations (lid, city, country) values (734, 'San Jose', 'Mexico');
insert into Locations (lid, city, country) values (735, 'Polyarnyy', 'Russia');
insert into Locations (lid, city, country) values (736, 'Edineţ', 'Moldova');
insert into Locations (lid, city, country) values (737, 'Nukuoro', 'Micronesia');
insert into Locations (lid, city, country) values (738, 'Hikari', 'Japan');
insert into Locations (lid, city, country) values (739, 'Roshnik', 'Albania');
insert into Locations (lid, city, country) values (740, 'Auas', 'Honduras');
insert into Locations (lid, city, country) values (741, 'Brinkmann', 'Argentina');
insert into Locations (lid, city, country) values (742, 'Dayushu', 'China');
insert into Locations (lid, city, country) values (743, 'Okinawa', 'Japan');
insert into Locations (lid, city, country) values (744, 'Anping', 'China');
insert into Locations (lid, city, country) values (745, 'Jingcheng', 'China');
insert into Locations (lid, city, country) values (746, 'Made', 'Indonesia');
insert into Locations (lid, city, country) values (747, 'Steblevë', 'Albania');
insert into Locations (lid, city, country) values (748, 'Holýšov', 'Czech Republic');
insert into Locations (lid, city, country) values (749, 'Zelenograd', 'Russia');
insert into Locations (lid, city, country) values (750, 'Lysekil', 'Sweden');
insert into Locations (lid, city, country) values (751, 'Heshui', 'China');
insert into Locations (lid, city, country) values (752, 'Olocuilta', 'El Salvador');
insert into Locations (lid, city, country) values (753, 'Saltpond', 'Ghana');
insert into Locations (lid, city, country) values (754, 'Tegalsari', 'Indonesia');
insert into Locations (lid, city, country) values (755, 'Tavricheskoye', 'Russia');
insert into Locations (lid, city, country) values (756, 'Tomsk', 'Russia');
insert into Locations (lid, city, country) values (757, 'Aldeia do Bispo', 'Portugal');
insert into Locations (lid, city, country) values (758, 'Vahdat', 'Tajikistan');
insert into Locations (lid, city, country) values (759, 'Thessaloníki', 'Greece');
insert into Locations (lid, city, country) values (760, 'San Francisco', 'Mexico');
insert into Locations (lid, city, country) values (761, 'Undurkhaan', 'Mongolia');
insert into Locations (lid, city, country) values (762, 'Sangongqiao', 'China');
insert into Locations (lid, city, country) values (763, 'Lewin Kłodzki', 'Poland');
insert into Locations (lid, city, country) values (764, 'Sacramento', 'United States');
insert into Locations (lid, city, country) values (765, 'Hostomice', 'Czech Republic');
insert into Locations (lid, city, country) values (766, 'Rogów', 'Poland');
insert into Locations (lid, city, country) values (767, 'Jixing', 'China');
insert into Locations (lid, city, country) values (768, 'Dzhalilabad', 'Azerbaijan');
insert into Locations (lid, city, country) values (769, 'San Cristóbal Cucho', 'Guatemala');
insert into Locations (lid, city, country) values (770, 'Aygestan', 'Armenia');
insert into Locations (lid, city, country) values (771, 'Kawengan', 'Indonesia');
insert into Locations (lid, city, country) values (772, 'Terentang', 'Indonesia');
insert into Locations (lid, city, country) values (773, 'Yacuíba', 'Bolivia');
insert into Locations (lid, city, country) values (774, 'Bailiang', 'China');
insert into Locations (lid, city, country) values (775, 'Bāsawul', 'Afghanistan');
insert into Locations (lid, city, country) values (776, 'Mundri', 'Indonesia');
insert into Locations (lid, city, country) values (777, 'El Peñol', 'Colombia');
insert into Locations (lid, city, country) values (778, 'Alibunan', 'Philippines');
insert into Locations (lid, city, country) values (779, 'Bagalangit', 'Philippines');
insert into Locations (lid, city, country) values (780, 'Telaga', 'Indonesia');
insert into Locations (lid, city, country) values (781, 'København', 'Denmark');
insert into Locations (lid, city, country) values (782, 'Cachada', 'Portugal');
insert into Locations (lid, city, country) values (783, 'Santa Teresa First', 'Philippines');
insert into Locations (lid, city, country) values (784, 'Palama', 'Indonesia');
insert into Locations (lid, city, country) values (785, 'Chillia', 'Peru');
insert into Locations (lid, city, country) values (786, 'Quilmes', 'Argentina');
insert into Locations (lid, city, country) values (787, 'Sambogunung', 'Indonesia');
insert into Locations (lid, city, country) values (788, 'Cankuzo', 'Burundi');
insert into Locations (lid, city, country) values (789, 'Diébougou', 'Burkina Faso');
insert into Locations (lid, city, country) values (790, 'Shangyuan', 'China');
insert into Locations (lid, city, country) values (791, 'Forino', 'Macedonia');
insert into Locations (lid, city, country) values (792, 'Legionowo', 'Poland');
insert into Locations (lid, city, country) values (793, 'Shencun', 'China');
insert into Locations (lid, city, country) values (794, 'Koror Town', 'Palau');
insert into Locations (lid, city, country) values (795, 'Rathnew', 'Ireland');
insert into Locations (lid, city, country) values (796, 'Luwingu', 'Zambia');
insert into Locations (lid, city, country) values (797, 'Praia da Barra', 'Portugal');
insert into Locations (lid, city, country) values (798, 'Umuquena', 'Venezuela');
insert into Locations (lid, city, country) values (799, 'Tomay Kichwa', 'Peru');
insert into Locations (lid, city, country) values (800, 'Aripuanã', 'Brazil');
insert into Locations (lid, city, country) values (801, 'Hvozdná', 'Czech Republic');
insert into Locations (lid, city, country) values (802, 'Gulyantsi', 'Bulgaria');
insert into Locations (lid, city, country) values (803, 'Francos', 'Portugal');
insert into Locations (lid, city, country) values (804, 'Nyangao', 'Tanzania');
insert into Locations (lid, city, country) values (805, 'Roboré', 'Bolivia');
insert into Locations (lid, city, country) values (806, 'Suibara', 'Japan');
insert into Locations (lid, city, country) values (807, 'Koror', 'Palau');
insert into Locations (lid, city, country) values (808, 'Chuanshan', 'China');
insert into Locations (lid, city, country) values (809, 'Gameleira', 'Brazil');
insert into Locations (lid, city, country) values (810, 'Västerås', 'Sweden');
insert into Locations (lid, city, country) values (811, 'Sandakan', 'Malaysia');
insert into Locations (lid, city, country) values (812, 'Nybro', 'Sweden');
insert into Locations (lid, city, country) values (813, 'Río Segundo', 'Argentina');
insert into Locations (lid, city, country) values (814, 'Kokopo', 'Papua New Guinea');
insert into Locations (lid, city, country) values (815, 'Futuroscope', 'France');
insert into Locations (lid, city, country) values (816, 'Yutan', 'China');
insert into Locations (lid, city, country) values (817, 'Pyay', 'Myanmar');
insert into Locations (lid, city, country) values (818, 'Canutama', 'Brazil');
insert into Locations (lid, city, country) values (819, 'Villa Gesell', 'Argentina');
insert into Locations (lid, city, country) values (820, 'Luoxi', 'China');
insert into Locations (lid, city, country) values (821, 'Sarzedo', 'Brazil');
insert into Locations (lid, city, country) values (822, 'Klutuk', 'Indonesia');
insert into Locations (lid, city, country) values (823, 'Dourados', 'Brazil');
insert into Locations (lid, city, country) values (824, 'Rāiwind', 'Pakistan');
insert into Locations (lid, city, country) values (825, 'Evansville', 'United States');
insert into Locations (lid, city, country) values (826, 'Chengyue', 'China');
insert into Locations (lid, city, country) values (827, 'Punta Alta', 'Argentina');
insert into Locations (lid, city, country) values (828, 'Kirove', 'Ukraine');
insert into Locations (lid, city, country) values (829, 'Río Sereno', 'Panama');
insert into Locations (lid, city, country) values (830, 'Kungur', 'Russia');
insert into Locations (lid, city, country) values (831, 'Baleal', 'Portugal');
insert into Locations (lid, city, country) values (832, 'Marco', 'Brazil');
insert into Locations (lid, city, country) values (833, 'San Bernardino', 'Paraguay');
insert into Locations (lid, city, country) values (834, 'Richmond', 'United States');
insert into Locations (lid, city, country) values (835, 'Tengah', 'Indonesia');
insert into Locations (lid, city, country) values (836, 'San Agustin', 'Philippines');
insert into Locations (lid, city, country) values (837, 'Hesheng', 'China');
insert into Locations (lid, city, country) values (838, 'Berģi', 'Latvia');
insert into Locations (lid, city, country) values (839, 'Alukama', 'Indonesia');
insert into Locations (lid, city, country) values (840, 'Yanmenguan', 'China');
insert into Locations (lid, city, country) values (841, 'Traiguén', 'Chile');
insert into Locations (lid, city, country) values (842, 'Radeče', 'Slovenia');
insert into Locations (lid, city, country) values (843, 'Guarda Nova', 'Portugal');
insert into Locations (lid, city, country) values (844, 'Goge', 'Indonesia');
insert into Locations (lid, city, country) values (845, 'Jagupit', 'Philippines');
insert into Locations (lid, city, country) values (846, 'Malakwāl', 'Pakistan');
insert into Locations (lid, city, country) values (847, 'Bor', 'Russia');
insert into Locations (lid, city, country) values (848, 'Boka', 'Serbia');
insert into Locations (lid, city, country) values (849, 'Marang', 'Indonesia');
insert into Locations (lid, city, country) values (850, 'Ciawi', 'Indonesia');
insert into Locations (lid, city, country) values (851, 'San Antonio', 'United States');
insert into Locations (lid, city, country) values (852, 'Gaokan', 'China');
insert into Locations (lid, city, country) values (853, 'Miraflores', 'Portugal');
insert into Locations (lid, city, country) values (854, 'Krasnovishersk', 'Russia');
insert into Locations (lid, city, country) values (855, 'Alcorriol', 'Portugal');
insert into Locations (lid, city, country) values (856, 'El Fasher', 'Sudan');
insert into Locations (lid, city, country) values (857, 'Shanhe', 'China');
insert into Locations (lid, city, country) values (858, 'Kerva', 'Russia');
insert into Locations (lid, city, country) values (859, 'Mierzęcice', 'Poland');
insert into Locations (lid, city, country) values (860, 'Dahu', 'Indonesia');
insert into Locations (lid, city, country) values (861, 'Kerkrade', 'Netherlands');
insert into Locations (lid, city, country) values (862, 'Renfengzhuang', 'China');
insert into Locations (lid, city, country) values (863, 'Francisco I Madero', 'Mexico');
insert into Locations (lid, city, country) values (864, 'Wakuya', 'Japan');
insert into Locations (lid, city, country) values (865, 'Xujia', 'China');
insert into Locations (lid, city, country) values (866, 'Ottawa', 'Canada');
insert into Locations (lid, city, country) values (867, 'Mineralnye Vody', 'Russia');
insert into Locations (lid, city, country) values (868, 'Margahayu', 'Indonesia');
insert into Locations (lid, city, country) values (869, 'Devin', 'Bulgaria');
insert into Locations (lid, city, country) values (870, 'Kebunkelapa', 'Indonesia');
insert into Locations (lid, city, country) values (871, 'Trzin', 'Slovenia');
insert into Locations (lid, city, country) values (872, 'Sanli', 'China');
insert into Locations (lid, city, country) values (873, 'Mariental', 'Namibia');
insert into Locations (lid, city, country) values (874, 'Runjin', 'China');
insert into Locations (lid, city, country) values (875, 'Hongor', 'Mongolia');
insert into Locations (lid, city, country) values (876, 'Qiaozhen', 'China');
insert into Locations (lid, city, country) values (877, 'Xihuaiba', 'China');
insert into Locations (lid, city, country) values (878, 'La Serena', 'Chile');
insert into Locations (lid, city, country) values (879, '20 de Noviembre', 'Mexico');
insert into Locations (lid, city, country) values (880, 'Khasht’arrak', 'Armenia');
insert into Locations (lid, city, country) values (881, 'Novosmolinskiy', 'Russia');
insert into Locations (lid, city, country) values (882, 'Kowang Utara', 'Indonesia');
insert into Locations (lid, city, country) values (883, 'Tarnogskiy Gorodok', 'Russia');
insert into Locations (lid, city, country) values (884, 'Saltpond', 'Ghana');
insert into Locations (lid, city, country) values (885, 'Luleå', 'Sweden');
insert into Locations (lid, city, country) values (886, 'Kokologo', 'Burkina Faso');
insert into Locations (lid, city, country) values (887, 'San Quintin', 'Philippines');
insert into Locations (lid, city, country) values (888, 'Pirajuí', 'Brazil');
insert into Locations (lid, city, country) values (889, 'Anolaima', 'Colombia');
insert into Locations (lid, city, country) values (890, 'La Roche-sur-Yon', 'France');
insert into Locations (lid, city, country) values (891, 'Kenscoff', 'Haiti');
insert into Locations (lid, city, country) values (892, 'Queimados', 'Brazil');
insert into Locations (lid, city, country) values (893, 'Dengteke', 'China');
insert into Locations (lid, city, country) values (894, 'Chinhoyi', 'Zimbabwe');
insert into Locations (lid, city, country) values (895, 'Strážnice', 'Czech Republic');
insert into Locations (lid, city, country) values (896, 'Tyszowce', 'Poland');
insert into Locations (lid, city, country) values (897, 'Gadon', 'Indonesia');
insert into Locations (lid, city, country) values (898, 'Ndewel', 'Indonesia');
insert into Locations (lid, city, country) values (899, 'Balangiga', 'Philippines');
insert into Locations (lid, city, country) values (900, 'Curumaní', 'Colombia');
insert into Locations (lid, city, country) values (901, 'Upper Hell''s Gate', 'Bonaire, Saint Eustatius and Saba ');
insert into Locations (lid, city, country) values (902, 'Severka', 'Russia');
insert into Locations (lid, city, country) values (903, 'Doko', 'Indonesia');
insert into Locations (lid, city, country) values (904, 'Magong', 'China');
insert into Locations (lid, city, country) values (905, 'Mangqu', 'China');
insert into Locations (lid, city, country) values (906, 'Rublëvo', 'Russia');
insert into Locations (lid, city, country) values (907, 'Donghai', 'China');
insert into Locations (lid, city, country) values (908, 'Fengqiao', 'China');
insert into Locations (lid, city, country) values (909, 'Isawa', 'Japan');
insert into Locations (lid, city, country) values (910, 'Morocelí', 'Honduras');
insert into Locations (lid, city, country) values (911, 'Táriba', 'Venezuela');
insert into Locations (lid, city, country) values (912, 'Baiquesi', 'China');
insert into Locations (lid, city, country) values (913, 'Jincang', 'China');
insert into Locations (lid, city, country) values (914, 'Pedra Azul', 'Brazil');
insert into Locations (lid, city, country) values (915, 'Wudil', 'Nigeria');
insert into Locations (lid, city, country) values (916, 'Grand Rapids', 'United States');
insert into Locations (lid, city, country) values (917, 'Gapyeong', 'South Korea');
insert into Locations (lid, city, country) values (918, 'Wanjia', 'China');
insert into Locations (lid, city, country) values (919, 'Fort Erie', 'Canada');
insert into Locations (lid, city, country) values (920, 'Indaiatuba', 'Brazil');
insert into Locations (lid, city, country) values (921, 'Fajsławice', 'Poland');
insert into Locations (lid, city, country) values (922, 'Touzao', 'China');
insert into Locations (lid, city, country) values (923, 'Gongchang', 'China');
insert into Locations (lid, city, country) values (924, 'Babice', 'Poland');
insert into Locations (lid, city, country) values (925, 'Zhaogezhuang', 'China');
insert into Locations (lid, city, country) values (926, 'Riangkroko', 'Indonesia');
insert into Locations (lid, city, country) values (927, 'Qinglin', 'China');
insert into Locations (lid, city, country) values (928, 'Poyang', 'China');
insert into Locations (lid, city, country) values (929, 'Krajan', 'Indonesia');
insert into Locations (lid, city, country) values (930, 'Daguyun', 'China');
insert into Locations (lid, city, country) values (931, 'Luokou', 'China');
insert into Locations (lid, city, country) values (932, 'Gandrungmangu', 'Indonesia');
insert into Locations (lid, city, country) values (933, 'Bāgh-e Maīdān', 'Afghanistan');
insert into Locations (lid, city, country) values (934, 'Sudimara', 'Indonesia');
insert into Locations (lid, city, country) values (935, 'Huayang', 'China');
insert into Locations (lid, city, country) values (936, 'Williamsfield', 'Jamaica');
insert into Locations (lid, city, country) values (937, 'Mahdia', 'Tunisia');
insert into Locations (lid, city, country) values (938, 'Nesovice', 'Czech Republic');
insert into Locations (lid, city, country) values (939, 'Amiens', 'France');
insert into Locations (lid, city, country) values (940, 'Campinho', 'Portugal');
insert into Locations (lid, city, country) values (941, 'Angered', 'Sweden');
insert into Locations (lid, city, country) values (942, 'Kuttu', 'Micronesia');
insert into Locations (lid, city, country) values (943, 'San Jose', 'Mexico');
insert into Locations (lid, city, country) values (944, 'Taokeng', 'China');
insert into Locations (lid, city, country) values (945, 'Bang Phae', 'Thailand');
insert into Locations (lid, city, country) values (946, 'La Esmeralda', 'Venezuela');
insert into Locations (lid, city, country) values (947, 'Metchosin', 'Canada');
insert into Locations (lid, city, country) values (948, 'Jiukeng', 'China');
insert into Locations (lid, city, country) values (949, 'Sendangagung', 'Indonesia');
insert into Locations (lid, city, country) values (950, 'Santa Cruz do Capibaribe', 'Brazil');
insert into Locations (lid, city, country) values (951, 'Chaoyang', 'China');
insert into Locations (lid, city, country) values (952, 'Žebrák', 'Czech Republic');
insert into Locations (lid, city, country) values (953, 'Şuwayr', 'Yemen');
insert into Locations (lid, city, country) values (954, 'Miguelópolis', 'Brazil');
insert into Locations (lid, city, country) values (955, 'Skoghall', 'Sweden');
insert into Locations (lid, city, country) values (956, 'Chinandega', 'Nicaragua');
insert into Locations (lid, city, country) values (957, 'Ambositra', 'Madagascar');
insert into Locations (lid, city, country) values (958, 'Urus-Martan', 'Russia');
insert into Locations (lid, city, country) values (959, 'Hayang', 'South Korea');
insert into Locations (lid, city, country) values (960, 'Nowshera Cantonment', 'Pakistan');
insert into Locations (lid, city, country) values (961, 'Kopayhorod', 'Ukraine');
insert into Locations (lid, city, country) values (962, 'San Fabian', 'Philippines');
insert into Locations (lid, city, country) values (963, 'Drammen', 'Norway');
insert into Locations (lid, city, country) values (964, 'Tulsa', 'United States');
insert into Locations (lid, city, country) values (965, 'Xiawa', 'China');
insert into Locations (lid, city, country) values (966, 'Runović', 'Croatia');
insert into Locations (lid, city, country) values (967, 'Itarana', 'Brazil');
insert into Locations (lid, city, country) values (968, 'Bayt Qād', 'Palestinian Territory');
insert into Locations (lid, city, country) values (969, 'Roslavl’', 'Russia');
insert into Locations (lid, city, country) values (970, 'Erpeldange', 'Luxembourg');
insert into Locations (lid, city, country) values (971, 'Oekuu', 'Indonesia');
insert into Locations (lid, city, country) values (972, 'Qazax', 'Azerbaijan');
insert into Locations (lid, city, country) values (973, 'Minneapolis', 'United States');
insert into Locations (lid, city, country) values (974, 'Chợ Lầu', 'Vietnam');
insert into Locations (lid, city, country) values (975, 'Bayanhoshuu', 'Mongolia');
insert into Locations (lid, city, country) values (976, 'Cuito', 'Angola');
insert into Locations (lid, city, country) values (977, 'Gambalidio', 'Philippines');
insert into Locations (lid, city, country) values (978, 'Maasin', 'Philippines');
insert into Locations (lid, city, country) values (979, 'Szczaniec', 'Poland');
insert into Locations (lid, city, country) values (980, 'Grujugan', 'Indonesia');
insert into Locations (lid, city, country) values (981, 'Chengui', 'China');
insert into Locations (lid, city, country) values (982, 'Deir Ḥannā', 'Israel');
insert into Locations (lid, city, country) values (983, 'Sacramento', 'Brazil');
insert into Locations (lid, city, country) values (984, 'Boevange-sur-Attert', 'Luxembourg');
insert into Locations (lid, city, country) values (985, 'Kebonkaret', 'Indonesia');
insert into Locations (lid, city, country) values (986, 'Kilifarevo', 'Bulgaria');
insert into Locations (lid, city, country) values (987, 'Moyogalpa', 'Nicaragua');
insert into Locations (lid, city, country) values (988, 'Novi Itebej', 'Serbia');
insert into Locations (lid, city, country) values (989, 'Shchigry', 'Russia');
insert into Locations (lid, city, country) values (990, 'Baru', 'Indonesia');
insert into Locations (lid, city, country) values (991, 'Nyrob', 'Russia');
insert into Locations (lid, city, country) values (992, 'Mengjia', 'China');
insert into Locations (lid, city, country) values (993, 'Drayton Valley', 'Canada');
insert into Locations (lid, city, country) values (994, 'Longxian', 'China');
insert into Locations (lid, city, country) values (995, 'Malunda', 'Indonesia');
insert into Locations (lid, city, country) values (996, 'Shuangqiao', 'China');
insert into Locations (lid, city, country) values (997, 'Veltruby', 'Czech Republic');
insert into Locations (lid, city, country) values (998, 'Sagara', 'Japan');
insert into Locations (lid, city, country) values (999, 'Sopla', 'Indonesia');
insert into Locations (lid, city, country) values (1000, 'Diofior', 'Senegal');
